name: Deploy Sanity Studio

on:
    push:
        branches:
            - main
        paths:
            - "studio-layer/**"
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy Sanity Studio
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: studio-layer

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: npm
                  cache-dependency-path: studio-layer/package-lock.json

            - name: Install Dependencies
              run: npm install

            - name: Build Sanity Studio
              run: npm run build

            - name: Deploy Sanity Studio
              env:
                  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
              run: npx sanity deploy --dataset production --hostname injective-blog --yes

            - name: Notify on Success
              if: success()
              run: echo "Sanity Studio deployed successfully!"

            - name: Notify on Failure
              if: failure()
              run: echo "Sanity Studio deployment failed!"
